# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8961014d192b2d429fbea9fbad579f50214f4d9d0623cd27a024faafa6122d092f4f41759dea79974e8908c3d7c3f89a3d3fbfcc58f702d142e2cad3da9a85c0

test:
  secret_key_base: 2abd36a5a98f9f82a063da1fbf84571299a34556288d3a9f6d293ae11e80552c821f11ae7c203000180ade73e471b2b078873cfa12b558e4f2a1d7c433c8b574

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
